let rooms = [
  {
    name: "entrance",
    objects: [
      {
        name: "front door",
        x: 300,
        y: 350,
        w: 80,
        h: 90,
        text: "No one is answering...",
        state: 0,
      },
      {
        name: "?",
        x: 530,
        y: 390,
        w: 60,
        h: 30,
        text:
          "I think that window might be open... is this breaking and entering?",
        state: 0,
      },
    ],
  },
  {
    name: "room1",
    objects: [
      {
        name: "skip",
        x: 510,
        y: 65,
        w: 50,
        h: 50,
      },
      {
        name: "bookshelf",
        x: 50,
        y: 100,
        w: 80,
        h: 300,
        text: "A dusty old bookshelf...",
        state: 0,
      },
      {
        name: "bed",
        x: 220,
        y: 280,
        w: 120,
        h: 120,
        text: "Even the bed is dusty.",
        state: 0,
      },
      {
        name: "chest",
        x: 480,
        y: 450,
        w: 60,
        h: 50,
        text:
          "There's a 3 number padlock on it. I should look for clues to figure out the code.",
        state: 0,
      },
      {
        name: "box",
        x: 17,
        y: 463,
        w: 60,
        h: 50,
        text:
          "There's an old newpaper inside. The front page reads 'Family suspected in money laundering conspiracy have fled the state'. The page number for page 3 is highlighted.",
        state: 0,
      },
      {
        name: "door",
        x: 500,
        y: 200,
        w: 80,
        h: 150,
        text: "Locked.",
        state: 0,
      },
      {
        name: "plant",
        x: 13,
        y: 33,
        w: 60,
        h: 50,
        text: "A small rag is placed under the plant pot.",
        state: 0,
      },
      {
        name: "frame",
        x: 175,
        y: 90,
        w: 60,
        h: 50,
        text:
          "This frame is covered in dust. I'm not touching it with my hands.",
        state: 0,
      },
      {
        name: "rug",
        x: 270,
        y: 460,
        w: 120,
        h: 50,
        text: "There's a 7 spray painted on the floor under the rug.",
        state: 0,
      },
      {
        name: "clock",
        x: 360,
        y: 200,
        w: 60,
        h: 30,
        text: "I don't think this clock works.",
        state: 0,
      },
    ],
  },
  {
    name: "room2",
    objects: [
      {
        name: "table",
        x: 247,
        y: 429,
        w: 120,
        h: 80,
        text:
          "A dirty tea cup was left here. I have a strange inclination to go wash it.",
        state: 0,
      },
      {
        name: "painting",
        x: 300,
        y: 100,
        w: 80,
        h: 120,
        text:
          "This weird painting has an annoying space between the canvas and the frame.",
        state: 0,
      },
      { name: "next room", x: 10, y: 290, w: 70, h: 50, text: "", state: 0 },
      {
        name: "bookshelf",
        x: 473,
        y: 145,
        w: 100,
        h: 150,
        text: "Some classic books.",
        state: 0,
      },
      {
        name: "couch",
        x: 282,
        y: 336,
        w: 70,
        h: 50,
        text: "Why is there a wrench between the cushions?",
        state: 0,
      },
      {
        name: "lamp",
        x: 99,
        y: 254,
        w: 70,
        h: 70,
        text: "Its dark in here.",
        state: 0,
      },
      {
        name: "drawer",
        x: 63,
        y: 394,
        w: 70,
        h: 80,
        text:
          "It's locked. There's a keypad under the words 'The best girl scout cookie flavor' (Type your answer)",
        state: 0,
      },
    ],
  },
  {
    name: "room3",
    text: "im in room 3",
    objects: [
      {
        name: "counter",
        x: 450,
        y: 370,
        w: 70,
        h: 80,
        text:
          "There's a pair of scissors on the counter, they may come in handy later.",
        state: 0,
      },
      {
        name: "right cabinets",
        x: 440,
        y: 186,
        w: 70,
        h: 80,
        text:
          "It's locked. The lock requires 3 shapes. The key options are a heart, circle, star, triangle, and square.",
        state: 0,
      },
      {
        name: "left cabinets",
        x: 95,
        y: 235,
        w: 70,
        h: 80,
        text:
          "Everything is normal kitchen stuff besides this permanent marker.",
        state: 0,
      },
      {
        name: "oven",
        x: 88,
        y: 419,
        w: 70,
        h: 80,
        text: "Somebody left a heart shaped cake in there.",
        state: 0,
      },
      {
        name: "sink",
        x: 281,
        y: 355,
        w: 70,
        h: 80,
        text: "It doesn't work.",
        state: 0,
      },
      {
        name: "under sink",
        x: 280,
        y: 440,
        w: 70,
        h: 80,
        text: "The pipe is loose.",
        state: 0,
      },
      {
        name: "windows",
        x: 270,
        y: 250,
        w: 70,
        h: 80,
        text: "The windows won't open.",
        state: 0,
      },
      { name: "next room", x: 15, y: 300, w: 80, h: 50, text: "", state: 0 },
      {
        name: "living room",
        x: 528,
        y: 310,
        w: 80,
        h: 50,
        text: " ",
        state: 0,
      },
    ],
  },
  {
    name: "room4",
    objects: [
      {
        name: "right lamp",
        x: 428,
        y: 225,
        w: 80,
        h: 50,
        text: "The lamp shade pattern resembles an M.",
        state: 0,
      },
      {
        name: "left lamp",
        x: 149,
        y: 218,
        w: 80,
        h: 80,
        text: "The lamp shade pattern resembles a T.",
        state: 0,
      },
      {
        name: "landscape painting",
        x: 18,
        y: 230,
        w: 70,
        h: 70,
        text:
          "This painting is odly geometric looking. I can just make out what might be a shape.",
        state: 0,
      },

      {
        name: "left drawers",
        x: 18,
        y: 390,
        w: 80,
        h: 80,
        text: "It's locked and needs a key.",
        state: 0,
      },
      {
        name: "drawers",
        x: 525,
        y: 395,
        w: 80,
        h: 80,
        text: "A... protractor?",
        state: 0,
      },
      {
        name: "keypad",
        x: 285,
        y: 345,
        w: 80,
        h: 100,
        text: " ",
        state: 0,
      },
      { name: "kitchen", x: 515, y: 270, w: 60, h: 50, text: "", state: 0 },
    ],
  },
  {
    name: "room5",
    objects: [
      {
        name: "Jewels?!",
        x: 99,
        y: 444,
        w: 120,
        h: 80,
        text: "Whoa, jackpot!",
        state: 0,
      },
      {
        name: "Upstairs",
        x: 169,
        y: 142,
        w: 120,
        h: 80,
        text: " ",
        state: 0,
      },
    ],
  },
  {
    name: "keyPad",
    objects: [
      {
        name: "0",
        x: 149,
        y: 190,
        w: 50,
        h: 50,
      },
      {
        name: "1",
        x: 245,
        y: 192,
        w: 50,
        h: 50,
      },
      {
        name: "2",
        x: 337,
        y: 193,
        w: 50,
        h: 50,
      },
      {
        name: "3",
        x: 431,
        y: 192,
        w: 50,
        h: 50,
      },
      {
        name: "4",
        x: 157,
        y: 271,
        w: 50,
        h: 50,
      },
      {
        name: "5",
        x: 245,
        y: 271,
        w: 50,
        h: 50,
      },
      {
        name: "6",
        x: 337,
        y: 271,
        w: 50,
        h: 50,
      },
      {
        name: "7",
        x: 431,
        y: 271,
        w: 50,
        h: 50,
      },
      {
        name: "8",
        x: 245,
        y: 351,
        w: 50,
        h: 50,
      },
      {
        name: "9",
        x: 337,
        y: 351,
        w: 50,
        h: 50,
      },
      {
        name: "check",
        x: 431,
        y: 351,
        w: 50,
        h: 50,
      },
      {
        name: "delete",
        x: 157,
        y: 351,
        w: 50,
        h: 50,
      },
      {
        name: "back",
        x: 150,
        y: 432,
        w: 50,
        h: 50,
      },
    ],
  },
  {
    name: "books",
    objects: [
      {
        name: "Shrek the Musical Script",
        x: 130,
        y: 135,
        w: 80,
        h: 90,
        text: "That's not even a book?",
        state: 0,
      },
      {
        name: "Twilight",
        x: 428,
        y: 130,
        w: 60,
        h: 30,
        text: "Ugh, such a classic.",
        state: 0,
      },
      {
        name: "Entrepreneurship for Dummies",
        x: 255,
        y: 438,
        w: 60,
        h: 30,
        text: "Oh?",
        state: 0,
      },
      {
        name: "The World's Smallest Prime Number",
        x: 5,
        y: 430,
        w: 60,
        h: 30,
        text: "Can't imagine why someone would buy this.",
        state: 0,
      },
    ],
  },
];
