let player = {
  hasKey: false,
  hasRag: false,
  rugInt: false,
  plantInt: false,
  chestInt: false,
  boxInt: false,
  hasWrench: false,
  hasCup: false,
  sinkFixed: false,
  hasHeart: false,
  hasScissor: false,
  hasKey2: false,
  hasMarker: false,
  hasStar: false,
  hasProtractor: false,
  hasTriangle: false,
  hasJewels: false,
  hasNote: false,
  hasShapeCode: false,
  };
